---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install stow and required tools
  apt:
    name:
      - stow
      - git
      - wget
      - unzip
    state: present
