---
- name: Remove existing bashrc stow
  command:
    cmd: stow -D bashrc
    chdir: "{{ dotfiles_path }}"
  ignore_errors: yes
  become_user: "{{ ansible_user_id }}"

- name: Check if source line exists in ~/.bashrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    regexp: '^\s*#?\s*source\s+~/.my_bashrc'
    line: 'source ~/.my_bashrc'
    state: present
  register: bashrc_result
  become_user: "{{ ansible_user_id }}"

- name: Apply bashrc stow
  command:
    cmd: stow bashrc
    chdir: "{{ dotfiles_path }}"
  become_user: "{{ ansible_user_id }}"

- name: Bashrc configuration complete
  debug:
    msg: "Bashrc configuration applied."
